### ISSUE TITLE
Signal Handler Error while compiling

### ISSUE THREAD

**Issue by malapatiravi** [ros/common_msgs#163]
Python version : 3.6.8
ROS: Kinetic, installed from source

I am trying to compile the common_msgs from source with python3.6.8 and i am getting the following error. 
could you please let me know if you have solution for this. I see this is more like python issue. But want confirmation if somebody has faced similar issue. 
Thank you!

```
dummy@dummy:~/catkin_sensor_msgs$ catkin build
-----------------------------------------------------------------------------
Profile:                     default
Extending:             [env] /home/dummy/ros_catkin_ws/install_isolated
Workspace:                   /home/dummy/catkin_sensor_msgs
-----------------------------------------------------------------------------
Build Space:        [exists] /home/dummy/catkin_sensor_msgs/build
Devel Space:        [exists] /home/dummy/catkin_sensor_msgs/devel
Install Space:     [missing] /home/dummy/catkin_sensor_msgs/install
Log Space:         [missing] /home/dummy/catkin_sensor_msgs/logs
Source Space:       [exists] /home/dummy/catkin_sensor_msgs/src
DESTDIR:            [unused] None
-----------------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        merged
-----------------------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
-----------------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
-----------------------------------------------------------------------------
Workspace configuration appears valid.

NOTE: Forcing CMake to run for each package.
-----------------------------------------------------------------------------
[build] Found '10' packages in 0.0 seconds.                                                                                                   
Starting  >>> catkin_tools_prebuild                                                                                                           
Finished  <<< catkin_tools_prebuild                [ 1.0 seconds ]                                                                            
Starting  >>> actionlib_msgs                                                                                                                  
Starting  >>> diagnostic_msgs                                                                                                                 
Starting  >>> geometry_msgs                                                                                                                   
Finished  <<< diagnostic_msgs                      [ 2.4 seconds ]                                                                            
Finished  <<< actionlib_msgs                       [ 2.5 seconds ]                                                                            
Finished  <<< geometry_msgs                        [ 4.2 seconds ]                                                                            
Starting  >>> nav_msgs                                                                                                                        
Starting  >>> sensor_msgs                                                                                                                     
Starting  >>> shape_msgs                                                                                                                      
Starting  >>> trajectory_msgs                                                                                                                 
Starting  >>> visualization_msgs                                                                                                              
Finished  <<< shape_msgs                           [ 2.6 seconds ]                                                                            
Finished  <<< trajectory_msgs                      [ 2.9 seconds ]                                                                            
Finished  <<< nav_msgs                             [ 4.4 seconds ]                                                                            
Finished  <<< visualization_msgs                   [ 3.8 seconds ]                                                                            
______________________________________________________________________________________________________________________________________________
Errors     << sensor_msgs:install /home/dummy/catkin_sensor_msgs/logs/sensor_msgs/build.install.000.log                                 
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --install-layout not recognized
CMake Error at catkin_generated/safe_execute_install.cmake:4 (message):
  
  execute_process(/home/dummy/catkin_sensor_msgs/build/sensor_msgs/catkin_generated/python_distutils_install.sh)
  returned error code
Call Stack (most recent call first):
  cmake_install.cmake:132 (include)


make: *** [install] Error 1
cd /home/dummy/catkin_sensor_msgs/build/sensor_msgs; catkin build --get-env sensor_msgs | catkin env -si  /usr/bin/make install; cd -
..............................................................................................................................................
Failed     << sensor_msgs:install                  [ Exited with code 2 ]                                                                     
Failed    <<< sensor_msgs                          [ 5.6 seconds ]                                                                            
Abandoned <<< stereo_msgs                          [ Unrelated job failed ]                                                                   
[build] Summary: 8 of 10 packages succeeded.                                                                                                  
[build]   Ignored:   1 packages were skipped or are blacklisted.                                                                              
[build]   Warnings:  None.                                                                                                                    
[build]   Abandoned: 1 packages were abandoned.                                                                                               
[build]   Failed:    1 packages failed.                                                                                                       
[build] Runtime: 11.6 seconds total.                                                                                                          
[build] Note: Workspace packages have changed, please re-source setup files to use them.
Exception ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/trollius/base_events.py", line 395, in __del__
  File "/usr/local/lib/python3.6/site-packages/trollius/unix_events.py", line 65, in close
  File "/usr/local/lib/python3.6/site-packages/trollius/unix_events.py", line 166, in remove_signal_handler
  File "/usr/local/lib/python3.6/signal.py", line 47, in signal
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object


```

**Comment by tfoote** [comment]
Yes, this looks like the setup.py options are different from what's expected. 

Please ask questions on http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments.
