### ISSUE TITLE
IMU messages cannot be converted to csv from bag file

### ISSUE THREAD

**Issue by dawonn** [ros/common_msgs#20]
Bag: https://www.dropbox.com/s/tie8svln73ii3ii/imu.bag

Command: rostopic echo -b imu.bag -p /android/imu

**Comment by tfoote** [comment]
The traceback is this: 

```
$ rostopic echo -b imu.bag -p /android/imu
Traceback (most recent call last):
  File "/opt/ros/hydro/bin/rostopic", line 35, in <module>
    rostopic.rostopicmain()
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rostopic/__init__.py", line 1666, in rostopicmain
    _rostopic_cmd_echo(argv)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rostopic/__init__.py", line 1026, in _rostopic_cmd_echo
    _rostopic_echo(topic, callback_echo, bag_file=options.bag)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rostopic/__init__.py", line 671, in _rostopic_echo
    _rostopic_echo_bag(callback_echo, bag_file)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rostopic/__init__.py", line 649, in _rostopic_echo_bag
    for t, msg, timestamp in b.read_messages():
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rosbag/bag.py", line 2062, in read_messages
    yield self.seek_and_read_message_data_record((entry.chunk_pos, entry.offset), raw)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rosbag/bag.py", line 2198, in seek_and_read_message_data_record
    msg_type = _get_message_type(connection_info)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rosbag/bag.py", line 1309, in _get_message_type
    message_type = genpy.dynamic.generate_dynamic(info.datatype, info.msg_def)[info.datatype]
  File "/opt/ros/hydro/lib/python2.7/dist-packages/genpy/dynamic.py", line 151, in generate_dynamic
    for l in msg_generator(msg_context, spec, search_path):
  File "/opt/ros/hydro/lib/python2.7/dist-packages/genpy/generator.py", line 733, in msg_generator
    genmsg.msg_loader.load_depends(msg_context, spec, search_path)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 344, in load_depends
    return load_msg_depends(msg_context, spec, msg_search_path)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 313, in load_msg_depends
    depspec = load_msg_by_type(msg_context, resolved_type, search_path)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 119, in load_msg_by_type
    file_path = get_msg_file(package_name, base_type, search_path)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 78, in get_msg_file
    % (base_type, package, search_path))
genmsg.msg_loader.MsgNotFound: Cannot locate message [Header]: unknown package [std_msgs] on search path [{}]
```

Same issue for groovy.

**Comment by dawonn** [comment]
Was I correct that the problem is in the package dependencies? 

I really don't understand where the problem is honestly, it was a blind guess posting here. :P

**Comment by tfoote** [comment]
no, it's a problem in the dynamic message introspection. Probably inside genpy. It works for non dynamic messages.

**Comment by dawonn** [comment]
ah, well I might have one more piece of info that could help:

I originally noticed this problem in the matlab_rosbag package, which is a cpp "plugin" for matlab. It appears that I can use matlab_rosbag to read other message types other than the IMU just fine for what it's worth.

It uses the dynamic message introspection, but (AFIK) does not use python.

**Comment by tfoote** [comment]
If you do a normal; 
rosbag play imu.bag
and 
rostopic echo /android/imu 

It will work fine.  rostopic -b dynamically generates the message definitions from the bag file which is what is a problem.

**Comment by tfoote** [comment]
What did you record your bag file with? It appears to have incomplete message definitions embedded in the bag file.

**Comment by dirk-thomas** [comment]
`genpy.dynamic.generate_dynamic()` fails since it is fed with an incomplete msg cat. According to the API doc it requires the full string representation including its depending messages (output of `gendeps --cat`).

Your bag file seem to only contain the Imu message definition but not its dependent message type. How (and when) did you record this bag file?

**Comment by chadrockey** [comment]
That topic matches android sensors driver, so this must be from rosjava.

**Comment by dawonn** [comment]
I used the ros sensors app from the android market for the IMU message topic.

i recorded the bag with 'rosbag record /android/imu'
Stopped the recording with ctrl+c, as usual.

**Comment by tfoote** [comment]
It looks like rosjava is not publishing the full message definition correctly. Could you refile this with rosjava?

**Comment by peci1** [comment]
For other googlers: it is not only rosjava, but this problem can arise whenever you use `ShapeShifter` for publishing and pass it a wrong message definition. That happens e.g. for custom multi-master systems, custom message storage (and replay) systems etc.
